### ISSUE TITLE
Cannot be used as a meson subproject (wrap)

### ISSUE THREAD

**Issue by dcbaker** [anholt/libepoxy#115]
`meson.source_root()` will always be the toplevel source root, so if libepoxy is used as a wrap the generation of epoxy_headers will fail since it will look in the for `include/epoxy` in the parent project, not in epoxy itself.

**Comment by ebassi** [comment]
Indeed, we use `meson.source_root()` twice:

 - once to find the `gen_dispatch.py` script, to work around a Meson bug that was already fixed a couple of releases ago
 - once to construct a full path to the headers in order to generate appropriate dependencies, as we refer to those files from different directories

Both should go away regardless.

**Comment by ebassi** [comment]
@dcbaker I've opened a PR that should fix the issue; testing is appreciated.
