### ISSUE TITLE
macos needs to wrap MakeCurrent and use dispatch table

### ISSUE THREAD

**Issue by wang-bin** [anholt/libepoxy#127]
Assume a thread has more than 1 context. dispatch_table should be rewritten when context changes. But from dispatch_common.h and gl_generated_dispatch.c I see the dispatch_table will not change because of using tls.
Using global ptr when dispatch table is disable is worse i think.

**Comment by ebassi** [comment]
Sorry, I don't have a good answer for this question.

Is there an actionable issue for me? Did you test the conditions you mention in your report, and verified that this is what happens?

**Comment by nigels-com** [comment]
Put another way, TLS associates the dispatch_table with a thread, but if the thread changes from one GL context to another it seems necessary to rebuild the dispatch table.

**Comment by wang-bin** [comment]
Here is an example on macOS to show multiple contexts in a single thread may give you wrong function ptr

- replace https://github.com/glfw/glfw/blob/master/tests/windows.c#L30 with `#include <epoxy/gl.h>`
- before glfwCreateWindow https://github.com/glfw/glfw/blob/master/tests/windows.c#L125 add the following lines

```
        if (i >= 2) {
            glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
            glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
            glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
            glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GLFW_TRUE);
        }
```

- remove glad function https://github.com/glfw/glfw/blob/master/tests/windows.c#L136
- add glGenVertexArrays code here https://github.com/glfw/glfw/blob/master/tests/windows.c#L138

```
    GLuint rb;
   glGenVertexArrays(1, &rb);
```

- build and run through apitrace, you will find `glGenVertexArraysAPPLE` is called even for gl4 core profile

- now change `if (i >= 2) {` to `if (i >= 0) {`, so all contexts are core profile, apitrace shows `glGenVertexArrays` is used for all contexts.

**Comment by nwnk** [comment]
So this seems to be saying that we need to treat Apple GL like WGL in terms of how GetProcAddress works. But that's both confusing and insufficient. It's confusing because on OSX we just dlsym for the right functions from OpenGL.framework, and one would think that dlsym's result wouldn't vary based on the current context. It's insufficient because if we _did_ want to mimic WGL we'd have to do a comparable trick for wrapping MakeCurrent, and at the moment epoxy doesn't have any native understanding of the OSX window system APIs (agl/cgl/nsgl) at all; the fact there are multiple probably means we'd need to make some policy decisions about which ones the caller may use.

Unless, of course, this is using epoxy as a frontend to GLX. But that'd be even weirder, because GLX is _specified_ to return context-independent function pointers from GetProcAddress, and AFAICT the Apple version of libGL doesn't go out of it's way to break that.

**Comment by wang-bin** [comment]
@nwnk  It's not about apple GL,WGL, dlsym and GetProcAddress. This example shows if context is changed, the dispatch table must be updated using dlsym or GetProcAddress, because the new context may have different core apis and extensions. Similar examples for wgl, glx should not be hard to write.

**Comment by nwnk** [comment]
@wang-bin sorry, that's not true. The [spec](https://www.khronos.org/registry/OpenGL/extensions/ARB/GLX_ARB_get_proc_address.txt) is quite clear about what you can do with the function pointers glXGetProcAddress gives you:

>     * Are function pointers context-independent?
>
 >       Yes. The pointer to an extension function can be used with any
 >       context which supports the extension.

This has [many implications](https://dri.freedesktop.org/wiki/glXGetProcAddressNeverReturnsNULL/) given that you can ask for the function pointer before _any_ context is created. Since it's not possible to know if the extension _will be_ supported, you have to return a pointer to code that will work if the bound context does support the extension. (If the ctx doesn't support it, then oh well, that's an application bug.)

[EGL](https://www.khronos.org/registry/EGL/specs/eglspec.1.5.pdf) behaves the same way:

>Client API function pointers returned by eglGetProcAddress are independent of the display and the currently bound client API context, and may be used by any client API context which supports the function.

In fact that's even a bit stronger because it means the same function pointer may be used for both GL and GLES contexts. This is why epoxy doesn't bother to maintain a dispatch_table for EGL or GLX: the function pointers are already context-independent, so it doesn't need to.

wglGetProcAddress, by contrast, does return context-dependent function pointers, so we need a dispatch table. And this bug appears to be describing a case on OSX where the same is true, presumably for a non-GLX context, although this is not made clear in the problem description. If you're saying this happens with GLX (or on something other than OSX or Windows) then someone has a bug and it isn't epoxy, though epoxy may want to work around it anyway.

We certainly _could_ always use a dispatch table and make GLX and EGL slightly slower, but the other problem would still remain: on (non-GLX) OSX we do not currently wrap anything like MakeCurrent, so we would not be able to rewrite the table when we change contexts.

**Comment by wang-bin** [comment]
Seems you are right. I look again at `glGenVertexArrays` from gl_generated_dispatch.c, if `USING_DISPATCH_TABLE` 0, which is default for mac, then `epoxy_glGenVertexArrays_resolver` is called every time.

```
static PFNGLGENVERTEXARRAYSPROC
epoxy_glGenVertexArrays_resolver(void)
{
    static const enum gl_provider providers[] = {
        Desktop_OpenGL_3_0,
        GL_extension_GL_ARB_vertex_array_object,
        OpenGL_ES_3_0,
        GL_extension_GL_APPLE_vertex_array_object,
        GL_extension_GL_OES_vertex_array_object,
        gl_provider_terminator
    };
    static const uint32_t entrypoints[] = {
        16784 /* "glGenVertexArrays" */,
        16784 /* "glGenVertexArrays" */,
        16784 /* "glGenVertexArrays" */,
        16802 /* "glGenVertexArraysAPPLE" */,
        16825 /* "glGenVertexArraysOES" */,
    };
    return gl_provider_resolver(entrypoint_strings + 16784 /* "glGenVertexArrays" */,
                                providers, entrypoints);
}
```

Looks like context version and extensions are already checked. But why a wrong function is called in my example?

If `USING_DISPATCH_TABLE` is 1, `epoxy_XXX_resolver` is called every time too, so the result should be right. But now I have another question, is it expensive to call epoxy_XXX_resolver in every gl command?

**Comment by nwnk** [comment]
> Looks like context version and extensions are already checked. But why a wrong function is called in my example?

I mean, I don't have a Mac to test with, so I don't know what kind of GL context you're getting. But if I had to guess, I'd guess that merely asking glfw for a "core profile" is not enough, that the default is GL 1.0 and so you end up with GL 2.1 as the newest thing OSX has that's compatible with 1.0. In which case you probably don't have ARB_vertex_array_object and only the APPLE one.

> If USING_DISPATCH_TABLE is 1, epoxy_XXX_resolver is called every time too, so the result should be right. But now I have another question, is it expensive to call epoxy_XXX_resolver in every gl command?

It would be expensive to do that, but we don't, so it doesn't matter. We call the _resolver function only the first time that function is looked up for a given context (if USING_DISPATCH_TABLE, the first time it's called at all if not). That function calls `gl_provider_resolver`, which returns the appropriate function pointer, which we then save in the dispatch table (or globally), so the second time you call `glGenVertexArrays` you go directly to the right function instead of resolving it twice.

**Comment by ebassi** [comment]
Considering that GL support in macOS has been deprecated, I'm not very optimistic about this getting addressed.

**Comment by ebassi** [comment]
Nothing happened in 2 years and change ⇒ closing.
