### ISSUE TITLE
[Minor] Package release syncing 

### ISSUE THREAD

**Issue by rubyFeedback** [anholt/libepoxy#251]
Right now we can see the following:

On:

    https://download.gnome.org/sources/libepoxy/1.5/?C=M&O=D

Most current release is:

    https://download.gnome.org/sources/libepoxy/1.5/libepoxy-1.5.6.tar.xz

So version 1.5.6.

The most current release on github here is:

    https://github.com/anholt/libepoxy/releases
    https://github.com/anholt/libepoxy/releases/download/1.5.7/libepoxy-1.5.7.tar.xz

So version 1.5.7

However had, ebassi recently committed:

"ebassi Post-release version bump to 1.5.8"

So version 1.5.8.

This leads to a peculiar minor issue - three different versions co-existing as the
"most recent one"! :D

Note: I understand that syncing to ftp/https mirrors may take a while and what not,
but usually this relates only to two releases (the older one, and the most recent
one), so in this case I assume one version was skipped or forgotten. Probably
the 1.5.8 release at github? It's a super minor thing, so not even sure whether it
is worth reporting. I actually use the https://download.gnome.org/sources/ variant
rather than github, simply because it seems to be more easy to keep track of
it (unless you e. g. release and download all from github or gitlab ... my impression
has been that both github and gitlab made that syncing-part to other "older" 
servers harder or more of a maintenance burden; I noticed this in general with
different projects, many of which gave up their old release policy and simply
switched to github or gitlab, which is understandable).

**Comment by ebassi** [comment]
Please, don't use the issue tracker for user support.

I do the uploads to download.gnome.org mostly for convenience, not because it's necessary. The release archive generated by `meson dist` are attached to the release page on github, and that's the authoritative source for releases.

> This leads to a peculiar minor issue - three different versions co-existing as the
> "most recent one"! :D

No, it does not.

Checking out from Git will always yield the latest release; what's in the `master` branch will become Epoxy 1.5.8. You may notice that there is no 1.5.8 tag, as well.
