### ISSUE TITLE
CMake configuration file

### ISSUE THREAD

**Issue by yanxiang-wang** [anholt/libepoxy#290]
Hello, when I install this library using Vcpkg. They cannot show the note on how to use this library.
The reason is that the upstream didn't provide the Cmake configuration file 

[https://github.com/microsoft/vcpkg/issues/32651](https://github.com/microsoft/vcpkg/issues/32651)

**Comment by ebassi** [comment]
This is not a libepoxy issue: we're not going to add a CMake build to the project.

The vcpkg project should use the supported Meson build; failing that, they can maintain a CMake build downstream, though of course that also means they will need to support it themselves.

Since your issue is finding the installed libepoxy, you should use `FindPkgConfig(epoxy)`, as libepoxy relies on the pkg-config project to define compiler and linker flags.
