### ISSUE TITLE
libEpoxy crashes in Windows in Release mode due to CONSTRUCT macro not being called.

### ISSUE THREAD

**Issue by esacree** [anholt/libepoxy#77]
I'm trying to use libEpoxy 1.3.1 (using the epoxy1.dll) on Windows 10.  As recommended, I built the download using CMake 3.4.0 to generate the Visual Studio 2015 solution and projects.  I have the code compiling and linking in both Win32 and x64 on Windows.   Debug 32 bit and 64 bit both run my application fine.

However, both 32-bit or 64 bit Release mode will crash as soon as the first wglCreateContext call is made.  Tracked the problem down to the CONSTRUCT macro not being called during a Release build run.  The macro is called during the Debug run.  CONTSTRUCT gets the library initialized.  Since it isn't getting called in Release, the library's function pointers are not initialized.  Program throws an exception and exits in Release.

QUESTION:   Is there a workaround or a code fix available to get Epoxy's CONSTRUCT macro to execute for Windows Release builds?

Windows Build Notes:
1.  Added x64 configuration to CMAKE generated projects.
2.  Used __stdcall function calling convention for build consistency.
     a.  Changed the __cdecl call setting to _stdcall to be consistent with the settings in the code's macros.
     b.  Added EPOXY_CALLSPEC to the gl.h and wgl.h include file function prototypes  
3.  Added EPOXY_DLL and BUILD_WGL to Visual Studio C++ PreProcessor settings to make sure the link worked properly, Otherwise the dllimport was not on the prototype function calls and the linker couldn't link the Epoxy dll functions.  The linker's symbol names were not mangled properly otherwise.

Any help would be greatly appreciated!

Thanks!

esacree

**Comment by codekiddy2** [comment]
Hi esacree!
Where did you get CMAKE build configuration for libepoxy-1.3.1 ??
Please let me know, so that can download it and fix the problem, I have Visual Studio solution for libepoxy-1.2 that works fine for release builds, so we can exchange my configuration for yours.

what say you?

**Comment by esacree** [comment]
Hi,

 

I’ve just been looking at switching from GLEW to Epoxy for the last 2 days.  I believe that I got the CMAKE text files from the link to the fork mentioned on this thread:

 

https://github.com/Nephatrine/libepoxy 

https://github.com/Nephatrine/libepoxy/blob/master/CMakeLists.txt

 

I’ve attached the file.

I downloaded the standard CMAKE 3.4 installation from the site https://cmake.org/download/  File: cmake-3.4.0-win32-x86.exe

 

Please let me know if I can help more.

 

Thanks!

 

Elaine Acree

**Comment by codekiddy2** [comment]
Oh, thanks so much!!

I'll generate a solution with CMAKE, and see how it goes here.


I got modified libepoxy-1.2 from Fan Chun-wei's tutorial site, and created a VS 2015 solution for that package, you can try and see if that works.

It's also possible to build without VS solution, (ex. from command line)

Site:
https://wiki.gnome.org/action/show/Projects/GTK+/Win32/MSVCCompilationOfGTKStack?action=show&redirect=GTK%2B%2FWin32%2FMSVCCompilationOfGTKStack#libepoxy

Solution is in my repo, but please note that solution won't open without entry repo placed in:
D\Github\Visual-Studio-gtkmm. because of project properties.
anyway here you are:
https://github.com/codekiddy2/Visual-Studio-gtkmm/tree/master/projects/libepoxy-1.2/src/msvc-140


I give feedback on how it goes with CMAKE generated solution. hopefully it will work! :)

**Comment by codekiddy2** [comment]
I *think* I solved the issue (any corrections are very much welcome)

Here is what I did:

Opened Visual Studio x64 native cmd prompt
ran cmake-gui from cmd prompt.
configured and generated for release x64.
build solution and run test project one by one.

ALL TEST PROJECTS CRASHED.

Here is what I did to make them work:

set compiler optimization to *disabled* ( it was /O2 )
for both static and dll libepoxy as well as all test projects.
clean solution
rebuild solution
run test projects one by one

THEY ALL PASSED!

Please try to disable optimization and give feedback if that worked for you.

**Comment by esacree** [comment]
Yes!  I turned off the O2 compiler optimization in Release mode and the CONSTRUCT macro is now being executed in both Release builds.

I had already turned off the Link Time optimization and whole program optimization, but those changes did not solve it.

 

It’s a Microsoft Visual Studio 2015 compiler optimization bug.  I haven’t seen one of those for a while.  I will file a report with Microsoft.  

 

Thanks for the help, I really appreciate it!

**Comment by codekiddy2** [comment]
Hi,
I "redesigned" solution made by cmake for my needs, in addition I have also run tests as much as possible.

result is as follows:
It's not only that optimization must be set to "disabled" but also LTCG flag must turned off for both static and shared libepoxy build types.

Test projects can retain /O2 and /LTCG.

This must be either some bug with compiler optimization, or there is a bug with the code itself.
I don't know, I'm happy with current build as it is.

Anyway thank you a lot for providing a link to CMAKE files. you made my day!
I'll put redesigned solution into my repo since it's the best one I had so far so you can download it if you wish.

Cheers mate!

**Comment by esacree** [comment]
I logged a bug with Microsoft Visual Studio 2015 this morning.

The problem is likely to be a Compiler/Linker Optimization bug since it works in Debug with no optimization but does not work in Release mode with optimization. 

If a basic CONSTRUCT macro doesn’t work, it could be causing issues for other users as well.  Perhaps it will get fixed, eventually.

 

Thanks again for your help!

**Comment by ebassi** [comment]
Epoxy does not use CMake, and if you create your own alternative build system for Epoxy you're also going to be responsible to handle its failures.

Epoxy 1.4.0 has been released with [Meson](http://mesonbuild.com) support. I strongly encourage you to try building Epoxy with it and Visual Studio.
